### ISSUE TITLE
VDR freezes while zapping

### ISSUE THREAD

**Issue by srehm** [manio/vdr-plugin-dvbapi#104]
When zapping through encrypted channels my VDR sporadically freezes, e.g. the OSD remains unresponsive until the watchdog kicks in and restarts the VDR. I am not 100% sure whether this is related the the dvbapi plugin but I could not reproduce it on FTA channels up until now.

VDR version is 2.2.0
vdr-plugin-dvbapi is from git commit 5de51c3
oscam is revision 11211.

All of that is running on an up-to-date Debian Jessie.

I have attached the gdb backtrace at the moment the watchdog tries to kill VDR as well as the syslog entries produced by the VDR during the freeze with dvbapi loglevel 3.

Any help with this issue would be highly appreciated. If you need further information, just let me know.

[gdb.txt](https://github.com/manio/vdr-plugin-dvbapi/files/143277/gdb.txt)
[syslog.txt](https://github.com/manio/vdr-plugin-dvbapi/files/143278/syslog.txt)

**Comment by manio** [comment]
Hello
I don't see any problems in the syslog. All looks fine.
It's hard to tell what is causing this lock. The backtrace indicates that it may be related with no data from dvb - you have some poll() - but it is just a guess. Maybe a driver problem?
I'd ask on vdr-portal for this...

**Comment by srehm** [comment]
Looks like you are right. I exchanged the DVB card with one from another system and the freezes seem to be gone. Thanks for the tip. I am closing this for now.
