### ISSUE TITLE
"unknown command" error, oscam >= r11169

### ISSUE THREAD

**Issue by glenvt18** [manio/vdr-plugin-dvbapi#107]
It may be related to #102. Every time I change the number of channels in TS stream (all from the same transponder) I get [this](http://pastebin.com/15Hz0YN1) "unknown command" error. Restarting oscam on the fly helps to recover.  The sequence is like this:
1 channel -> ok
2 channels -> error
restart oscam -> ok
1 channel -> error
restart oscam -> ok
I've bisected oscam from r10389 to r11211 and found that it happens starting from r11169. Everything works fine with r11168. oscam is in socket mode (not network).

**Comment by manio** [comment]
Can you check it in network mode?

**Comment by glenvt18** [comment]
Just checked. Yes it works with r11169 and r11211 up to 3 channels. Is the socket mode considered obsolete?

**Comment by manio** [comment]
Yes it is (but not mentioned in the plugin yet), read my update above^^^.
Please just use network mode, socket mode will be removed. Network mode is more flexible and has a proper protocol versioning, and maintaing the old compatibility with socket mode (which is btw shared with other standard STBs in oscam) is a lot of work.

**Comment by glenvt18** [comment]
OK. Thank you very much.
