### ISSUE TITLE
OSD-Teletext

### ISSUE THREAD

**Issue by Norbert01** [manio/vdr-plugin-dvbapi#108]
With the vdr plugin osd-teletext, the vdr often crash if I record a scrambled stream and zap to another scrambled program (no always, but very often). Is this a issue of dvbapi or osd-teletext? 

Mar 19 22:39:32 yavdr vdr: [4878] switching to channel 37 (Eurosport 1 Deutschland)
Mar 19 22:39:32 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:39:32 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:39:32 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:39:32 yavdr vdr: [22496] osdteletext-receiver thread ended (pid=4878, tid=22496)
Mar 19 22:39:32 yavdr vdr: [4878] buffer stats: 0 (0%) used
Mar 19 22:39:32 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:32 yavdr vdr: message repeated 3 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:32 yavdr vdr: [22499] device 1 TS buffer thread ended (pid=4878, tid=22499)
Mar 19 22:39:32 yavdr vdr: [22495] buffer stats: 53204 (1%) used
Mar 19 22:39:32 yavdr vdr: [22495] device 1 receiver thread ended (pid=4878, tid=22495)
Mar 19 22:39:32 yavdr vdr: [22511] device 1 receiver thread started (pid=4878, tid=22511, prio=high)
Mar 19 22:39:32 yavdr vdr: [4878] creating directory /var/run/vdr/vtx/S19.2E-1-1091-31200
Mar 19 22:39:32 yavdr vdr: [22512] device 1 TS buffer thread started (pid=4878, tid=22512, prio=high)
Mar 19 22:39:32 yavdr vdr: [22513] osdteletext-receiver thread started (pid=4878, tid=22513, prio=high)
Mar 19 22:39:32 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:33 yavdr vdr: message repeated 9 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:33 yavdr vdr: video: slow down video, duping frame
Mar 19 22:39:33 yavdr vdr: video: decoder buffer empty, duping frame (16246/78) 0 v-buf
Mar 19 22:39:33 yavdr vdr: video: --:--:--.---   +0    0   0/\ms   0+5+4 v-buf
Mar 19 22:39:33 yavdr vdr: [22497] blinking thread ended (pid=4878, tid=22497)
Mar 19 22:39:33 yavdr vdr: [22518] blinking thread started (pid=4878, tid=22518, prio=high)
Mar 19 22:39:33 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:34 yavdr vdr: [4878] [softhddev]SetPlayMode: 1
Mar 19 22:39:34 yavdr vdr: audio/alsa: using device 'default'
Mar 19 22:39:34 yavdr vdr: audio/alsa: start delay 500ms
Mar 19 22:39:34 yavdr vdr: [4878] switching to channel 38 (Comedy Central/VIVA)
Mar 19 22:39:34 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:39:34 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:39:34 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:39:34 yavdr vdr: [22513] osdteletext-receiver thread ended (pid=4878, tid=22513)
Mar 19 22:39:34 yavdr vdr: [4878] buffer stats: 0 (0%) used
Mar 19 22:39:34 yavdr vdr: [22512] device 1 TS buffer thread ended (pid=4878, tid=22512)
Mar 19 22:39:34 yavdr vdr: [22511] buffer stats: 82156 (1%) used
Mar 19 22:39:34 yavdr vdr: [22511] device 1 receiver thread ended (pid=4878, tid=22511)
Mar 19 22:39:34 yavdr vdr: [22521] device 1 receiver thread started (pid=4878, tid=22521, prio=high)
Mar 19 22:39:34 yavdr vdr: [22522] device 1 TS buffer thread started (pid=4878, tid=22522, prio=high)
Mar 19 22:39:34 yavdr vdr: [22523] osdteletext-receiver thread started (pid=4878, tid=22523, prio=high)
Mar 19 22:39:35 yavdr vdr: [22518] blinking thread ended (pid=4878, tid=22518)
Mar 19 22:39:35 yavdr vdr: [22526] blinking thread started (pid=4878, tid=22526, prio=high)
Mar 19 22:39:35 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:35 yavdr vdr: [4878] [softhddev]SetPlayMode: 1
Mar 19 22:39:35 yavdr vdr: [4878] switching to channel 39 (DELUXE MUSIC)
Mar 19 22:39:35 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:39:35 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:39:35 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:39:35 yavdr vdr: [22523] osdteletext-receiver thread ended (pid=4878, tid=22523)
Mar 19 22:39:35 yavdr vdr: [4878] buffer stats: 0 (0%) used
Mar 19 22:39:35 yavdr vdr: [22522] device 1 TS buffer thread ended (pid=4878, tid=22522)
Mar 19 22:39:35 yavdr vdr: [22521] buffer stats: 53392 (1%) used
Mar 19 22:39:35 yavdr vdr: [22521] device 1 receiver thread ended (pid=4878, tid=22521)
Mar 19 22:39:35 yavdr vdr: [22528] device 1 receiver thread started (pid=4878, tid=22528, prio=high)
Mar 19 22:39:35 yavdr vdr: [22529] device 1 TS buffer thread started (pid=4878, tid=22529, prio=high)
Mar 19 22:39:36 yavdr vdr: [22526] blinking thread ended (pid=4878, tid=22526)
Mar 19 22:39:36 yavdr vdr: [22532] blinking thread started (pid=4878, tid=22532, prio=high)
Mar 19 22:39:36 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:37 yavdr vdr: [4878] [softhddev]SetPlayMode: 1
Mar 19 22:39:37 yavdr vdr: [softhddev] invalid PES video packet
Mar 19 22:39:37 yavdr vdr: [softhddev] 2 invalid PES video packet(s)
Mar 19 22:39:37 yavdr vdr: audio/alsa: using device 'default'
Mar 19 22:39:37 yavdr vdr: audio/alsa: start delay 500ms
Mar 19 22:39:37 yavdr vdr: [4878] switching to channel 40 (RTL HD)
Mar 19 22:39:37 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:39:37 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:39:37 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:39:37 yavdr vdr: [22529] device 1 TS buffer thread ended (pid=4878, tid=22529)
Mar 19 22:39:37 yavdr vdr: [22528] buffer stats: 38916 (0%) used
Mar 19 22:39:37 yavdr vdr: [22528] device 1 receiver thread ended (pid=4878, tid=22528)
Mar 19 22:39:37 yavdr vdr: [4878] CAM 1: assigned to device 1
Mar 19 22:39:37 yavdr vdr: [4878] DVBAPI: 0.0 set CAM decrypt (SID 61200 (0xEF10), caLm 4, HasCaDescriptors 1)
Mar 19 22:39:37 yavdr vdr: [22535] device 1 receiver thread started (pid=4878, tid=22535, prio=high)
Mar 19 22:39:37 yavdr vdr: [22537] device 1 TS buffer thread started (pid=4878, tid=22537, prio=high)
Mar 19 22:39:37 yavdr vdr: [22536] osdteletext-receiver thread started (pid=4878, tid=22536, prio=high)
Mar 19 22:39:38 yavdr vdr: [22532] blinking thread ended (pid=4878, tid=22532)
Mar 19 22:39:38 yavdr vdr: [22542] blinking thread started (pid=4878, tid=22542, prio=high)
Mar 19 22:39:38 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:38 yavdr vdr: [4878] [softhddev]SetPlayMode: 1
Mar 19 22:39:38 yavdr vdr: audio/alsa: using device 'default'
Mar 19 22:39:38 yavdr vdr: [softhddev] invalid PES video packet
Mar 19 22:39:38 yavdr vdr: audio/alsa: start delay 500ms
Mar 19 22:39:38 yavdr vdr: [softhddev] 2 invalid PES video packet(s)
Mar 19 22:39:39 yavdr vdr: video: decoder buffer empty, duping frame (16302/8) 0 v-buf
Mar 19 22:39:39 yavdr vdr: video/vdpau: missed frame (67/8)
Mar 19 22:39:39 yavdr vdr: video: decoder buffer empty, duping frame (16303/8) 0 v-buf
Mar 19 22:39:39 yavdr vdr: video: 20:35:35.316+8888    0   0/\ms   0+5+4 v-buf
Mar 19 22:39:39 yavdr vdr: audio/alsa: using pass-through device 'default'
Mar 19 22:39:39 yavdr vdr: audio/alsa: start delay 500ms
Mar 19 22:39:39 yavdr vdr: video: decoder buffer empty, duping frame (16307/12) 0 v-buf
Mar 19 22:39:39 yavdr vdr: video: slow down video, duping frame
Mar 19 22:39:39 yavdr vdr: video: 20:35:35.776+1276  622   0/\ms   3+8+4 v-buf
Mar 19 22:39:39 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:41 yavdr vdr: message repeated 71 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:41 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:41 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:42 yavdr vdr: message repeated 10 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:42 yavdr vdr: video/vdpau: synced after 163 frames
Mar 19 22:39:42 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:43 yavdr vdr: message repeated 43 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:43 yavdr vdr: [22542] blinking thread ended (pid=4878, tid=22542)
Mar 19 22:39:43 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: message repeated 345 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]CreateOsd: 0, 0, 0, using OpenGL OSD support
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]cOglOsd osdLeft 0 osdTop 0 screenWidth 1920 screenHeight 1080
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: message repeated 6 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:54 yavdr vdr: [4878] switching to channel 41 (SAT.1 HD)
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: [4878] DVBAPI: 0.0 set CAM decrypt (SID 61200 (0xEF10), caLm 5, HasCaDescriptors 1)
Mar 19 22:39:54 yavdr vdr: [4878] CAM 1: unassigned
Mar 19 22:39:54 yavdr vdr: [22536] osdteletext-receiver thread ended (pid=4878, tid=22536)
Mar 19 22:39:54 yavdr vdr: [4878] buffer stats: 0 (0%) used
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: message repeated 6 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:54 yavdr vdr: [22537] device 1 TS buffer thread ended (pid=4878, tid=22537)
Mar 19 22:39:54 yavdr vdr: [22535] buffer stats: 476768 (9%) used
Mar 19 22:39:54 yavdr vdr: [22535] device 1 receiver thread ended (pid=4878, tid=22535)
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: [22588] osdteletext-receiver thread started (pid=4878, tid=22588, prio=high)
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]Maximum size for GPU cache reached. Used: 128,00MB Max: 128,00MB
Mar 19 22:39:54 yavdr vdr: [22591] fadable thread started (pid=4878, tid=22591, prio=high)
Mar 19 22:39:54 yavdr vdr: [22590] blinking thread started (pid=4878, tid=22590, prio=high)
Mar 19 22:39:54 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:54 yavdr vdr: message repeated 4 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:54 yavdr vdr: [4878] [softhddev]SetPlayMode: 1
Mar 19 22:39:54 yavdr vdr: [22592] fadable thread started (pid=4878, tid=22592, prio=high)
Mar 19 22:39:54 yavdr vdr: audio/alsa: using pass-through device 'default'
Mar 19 22:39:54 yavdr vdr: audio/alsa: start delay 500ms
Mar 19 22:39:54 yavdr vdr: [22591] fadable thread ended (pid=4878, tid=22591)
Mar 19 22:39:55 yavdr vdr: [22592] fadable thread ended (pid=4878, tid=22592)
Mar 19 22:39:55 yavdr vdr: video: slow down video, duping frame
Mar 19 22:39:55 yavdr vdr: video: decoder buffer empty, duping frame (16371/762) 0 v-buf
Mar 19 22:39:55 yavdr vdr: video: --:--:--.---   +0    0   0/\ms   0+5+4 v-buf
Mar 19 22:39:56 yavdr vdr: video: decoder buffer empty, duping frame (16405/14) 2 v-buf
Mar 19 22:39:56 yavdr vdr: video: slow down video, duping frame
Mar 19 22:39:56 yavdr vdr: video:  1:43:23.537 +923  492   0/\ms   3+7+4 v-buf
Mar 19 22:39:56 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:58 yavdr vdr: message repeated 59 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:58 yavdr vdr: video/vdpau: synced after 117 frames
Mar 19 22:39:58 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:39:59 yavdr vdr: message repeated 32 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:39:59 yavdr vdr: [22590] blinking thread ended (pid=4878, tid=22590)
Mar 19 22:39:59 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:40:03 yavdr vdr: message repeated 139 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:40:03 yavdr vdr: [4878] [softhddev]CreateOsd: 0, 0, 0, using OpenGL OSD support
Mar 19 22:40:03 yavdr vdr: [4878] [softhddev]cOglOsd osdLeft 0 osdTop 0 screenWidth 1920 screenHeight 1080
Mar 19 22:40:03 yavdr vdr: [4878] [softhddev]CreateOsd: 0, 0, 0, using OpenGL OSD support
Mar 19 22:40:03 yavdr vdr: [4878] [softhddev]cOglOsd osdLeft 0 osdTop 0 screenWidth 1920 screenHeight 1080
Mar 19 22:40:03 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:40:03 yavdr vdr: message repeated 3 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:40:03 yavdr vdr: audio/alsa: broken driver 220 state 'RUNNING'
Mar 19 22:40:03 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:40:03 yavdr vdr: message repeated 2 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:40:04 yavdr vdr: [4878] switching to channel 42 (ProSieben HD)
Mar 19 22:40:04 yavdr vdr: [4878] [softhddev]SetPlayMode: 0
Mar 19 22:40:04 yavdr vdr: [4878] [softhddev]SetVideoDisplayFormat: 1
Mar 19 22:40:04 yavdr vdr: [4878] [softhddev]GetSpuDecoder:
Mar 19 22:40:04 yavdr vdr: [22588] osdteletext-receiver thread ended (pid=4878, tid=22588)
Mar 19 22:40:04 yavdr vdr: audio/alsa: broken driver 0 state 'RUNNING'
Mar 19 22:40:04 yavdr vdr: message repeated 11 times: [ audio/alsa: broken driver 0 state 'RUNNING']
Mar 19 22:40:04 yavdr vdr: video: slow down video, duping frame
Mar 19 22:40:04 yavdr vdr: video: decoder buffer empty, duping frame (16451/374) 0 v-buf
Mar 19 22:40:04 yavdr vdr: video: --:--:--.---   +0    0   0/\ms   0+5+4 v-buf
Mar 19 22:40:05 yavdr vdr: [19372] i/o throttle activated, count = 1 (tid=19372)
Mar 19 22:40:06 yavdr vdr: [19372] buffer usage: 70% (tid=19371)
Mar 19 22:40:06 yavdr vdr: [19372] buffer usage: 80% (tid=19371)
Mar 19 22:40:07 yavdr vdr: [19372] buffer usage: 90% (tid=19371)
Mar 19 22:40:07 yavdr vdr: [19372] buffer usage: 100% (tid=19371)
Mar 19 22:40:21 yavdr markad: [19374] recording interrupted, waiting for continuation...
Mar 19 22:40:33 yavdr vdr: [19370] ERROR: video data stream broken
Mar 19 22:40:33 yavdr vdr: [19370] initiating emergency exit
Mar 19 22:40:40 yavdr kernel: [20744.296765] init: vdr main process (4878) killed by KILL signal
Mar 19 22:40:40 yavdr kernel: [20744.298374] init: vdr-net-monitor main process (5041) killed by TERM signal
Mar 19 22:40:40 yavdr kernel: [20744.302685] init: vdr-update-monitor main process (5044) killed by TERM signal

**Comment by manio** [comment]
No idea. Do you have a backtrace? What plugin version you are using?

**Comment by Norbert01** [comment]
backtrace: http://paste.ubuntu.com/15438047/

vdr-plugin-osdteletext (0.9.5-1yavdr1~trusty)
vdr-plugin-dvbapi (2:2.2.2-11-gc76c24e-2yavdr0~trusty)

**Comment by manio** [comment]
Can you try to disable dynamite plugin?

**Comment by Norbert01** [comment]
It works without dynamite, thanks.

**Comment by manio** [comment]
Ok, thanks.
