### ISSUE TITLE
stop decoding BISS caid 2600

### ISSUE THREAD

**Issue by vasyl2** [manio/vdr-plugin-dvbapi#111]
Hi!

Сhannel runs for 30 seconds
the only problem with the coding BISS

Distr: YaVDR 0.6
vdr (2.2.0/2.2.0) - The Video Disk Recorder
dvbapi (2.2.3) - SoftCAM for OSCam
oscam-1.20-unstable_svn-r11228 x86_64-linux-gnu

May 26 22:19:53 htpc vdr: [20487] CAM 2: assigned to device 2
May 26 22:19:53 htpc vdr: [21164] streamdev-livestreaming thread started (pid=20396, tid=21164, prio=high)
May 26 22:19:53 htpc vdr: [21163] streamdev-writer thread started (pid=20396, tid=21163, prio=high)
May 26 22:19:53 htpc vdr: [20487] DVBAPI: 1.0 CA_PMT decoding len=17 lm=4 prg=6125 len=7
May 26 22:19:53 htpc vdr: [20487] DVBAPI: ci_cmd(G)=01
May 26 22:19:53 htpc vdr: [20487] DVBAPI: pid=2,17ee len=0 (0x0)
May 26 22:19:53 htpc vdr: [20487] DVBAPI: pid=4,17ef len=0 (0x0)
May 26 22:19:53 htpc vdr: [20487] DVBAPI: 1.0 got CA pmt ciCmd=1 caLm=4
May 26 22:19:53 htpc vdr: [20487] DVBAPI: 1.0 answer to query suppressed
May 26 22:19:53 htpc vdr: [20487] DVBAPI: 1.0 set CAM decrypt (SID 6125 (0x17ED), caLm 4, HasCaDescriptors 1)
May 26 22:19:53 htpc vdr: [20487] DVBAPI: send: channelSid=0x17ed (6125)
May 26 22:19:53 htpc vdr: [20487] DVBAPI: Write, sock=85
May 26 22:19:53 htpc vdr: [20487] DVBAPI: socket_fd=85 len=33 wrote=33
May 26 22:19:53 htpc vdr: [20424] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=0, demux_idx=0, filter_num=0
May 26 22:19:53 htpc vdr: [20424] DVBAPI: SetFilter: adapter=1 set FILTER pid=0000 start=1, demux=0, filter=0
May 26 22:19:53 htpc vdr: [20424] DVBAPI:    --> FILTER: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:19:54 htpc vdr: [20424] DVBAPI:    -->   MASK: FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:19:54 htpc vdr: [20424] DVBAPI: SetFilter: inserting new filter, demux=0, filter_num=0
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=1FFF, demux_idx=0, filter_num=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=1FFF, demux_idx=0, filter_num=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_PID request, adapter_index=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 1.-1: set pid 0x17ee
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_PID request, adapter_index=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 1.0: set pid 0x17ee
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_PID request, adapter_index=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 1.-1: set pid 0x17ef
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_PID request, adapter_index=1
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 1.0: set pid 0x17ef
May 26 22:19:54 htpc vdr: [20424] DVBAPI: SetDescr
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 0: even key set
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_DESCR request, adapter_index=1, index=0
May 26 22:19:54 htpc vdr: [20424] DVBAPI: SetDescr
May 26 22:19:54 htpc vdr: [20424] DVBAPI: SetDescr
May 26 22:19:54 htpc vdr: [20424] DVBAPI: 0:  odd key set
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got CA_SET_DESCR request, adapter_index=1, index=0
May 26 22:19:54 htpc vdr: [20424] DVBAPI: Action: Got ECM_INFO: adapter_index=1, SID = 17ED, CAID = 2600 (biss), PID = 1FFF, ProvID = 000000, ECM time = 6 ms, reader = biss, from = vnc.org.ua, protocol = newcamd, hops = 0
May 26 22:19:54 htpc vdr: [20424] DVBAPI: UpdateEcmInfo: PMTO update, adapter=1, SID=17ED
May 26 22:19:54 htpc vdr: [21166] device 2 receiver thread started (pid=20396, tid=21166, prio=high)
May 26 22:19:54 htpc vdr: [21167] device 2 TS buffer thread started (pid=20396, tid=21167, prio=high)
May 26 22:20:04 htpc vdr: [20424] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=11, demux_idx=0, filter_num=2
May 26 22:20:04 htpc vdr: [20424] DVBAPI: SetFilter: adapter=1 set FILTER pid=0011 start=1, demux=0, filter=2
May 26 22:20:04 htpc vdr: [20424] DVBAPI:    --> FILTER: 42 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:20:04 htpc vdr: [20424] DVBAPI:    -->   MASK: FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:20:04 htpc vdr: [20424] DVBAPI: SetFilter: inserting new filter, demux=0, filter_num=2
May 26 22:20:04 htpc vdr: [21166] DVBAPI: Analyze: saving first part of data, tablelen=250
May 26 22:20:04 htpc vdr: [21166] DVBAPI: Analyze: PUSI=0, to_copy=70
May 26 22:20:04 htpc vdr: [21166] DVBAPI: Analyze: filter data assembled, sending len=253
May 26 22:20:04 htpc vdr: [21166] DVBAPI: Write, sock=85
May 26 22:20:04 htpc vdr: [21166] DVBAPI: socket_fd=85 len=259 wrote=259
May 26 22:20:04 htpc vdr: [20424] DVBAPI: Action: Got DMX_STOP request, adapter_index=1, pid=11, demux_idx=0, filter_num=2
May 26 22:20:04 htpc vdr: [20424] DVBAPI: SetFilter: adapter=1 set FILTER pid=0011 start=0, demux=0, filter=2
May 26 22:20:04 htpc vdr: [20424] DVBAPI: SetFilter: deleting filter, demux=0, filter_num=2
May 26 22:20:04 htpc vdr: [20424] DVBAPI: SetFilter: deleted the last filter for pid=0011, removing list
May 26 22:20:24 htpc vdr: [20424] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=1, demux_idx=0, filter_num=2
May 26 22:20:24 htpc vdr: [20424] DVBAPI: SetFilter: adapter=1 set FILTER pid=0001 start=1, demux=0, filter=2
May 26 22:20:24 htpc vdr: [20424] DVBAPI:    --> FILTER: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:20:24 htpc vdr: [20424] DVBAPI:    -->   MASK: FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
May 26 22:20:24 htpc vdr: [20424] DVBAPI: SetFilter: inserting new filter, demux=0, filter_num=2
May 26 22:20:24 htpc vdr: [21166] DVBAPI: Analyze: all data in one TS packet, immediate send
May 26 22:20:24 htpc vdr: [21166] DVBAPI: Write, sock=85
May 26 22:20:24 htpc vdr: [21166] DVBAPI: socket_fd=85 len=24 wrote=24
May 26 22:20:24 htpc vdr: [20424] DVBAPI: Action: Got DMX_STOP request, adapter_index=1, pid=1, demux_idx=0, filter_num=2
May 26 22:20:24 htpc vdr: [20424] DVBAPI: SetFilter: adapter=1 set FILTER pid=0001 start=0, demux=0, filter=2
May 26 22:20:24 htpc vdr: [20424] DVBAPI: SetFilter: deleting filter, demux=0, filter_num=2
May 26 22:20:24 htpc vdr: [20424] DVBAPI: SetFilter: deleted the last filter for pid=0001, removing list

**Comment by manio** [comment]
Did you try the expiration check (-d)?
https://github.com/manio/vdr-plugin-dvbapi/blob/master/README#L159

**Comment by vasyl2** [comment]
Hi!

Yes it works, thank you!

Sorry for the stupid question.

**Comment by noh950** [comment]
I have the same issue but I'm having defficulties starting vdr from the cmd, I usually start it with a script that comes from the repository I installed vdr from.
Is there another way to disable the expiration check ? 
Thanks

**Comment by manio** [comment]
> Is there another way to disable the expiration check ?

Modify a script? :)

**Comment by noh950** [comment]
Here is the bash text:
https://justpaste.it/1zsb1

can you give me a hand

**Comment by manio** [comment]
Wrong script. This is not a place to ask such questions. Please ask for help on your distro forum/IRC.

**Comment by noh950** [comment]
You're right 
thanks
