### ISSUE TITLE
Should read_sdt and write_sdt_prov work?

### ISSUE THREAD

**Issue by No0ne** [manio/vdr-plugin-dvbapi#114]
While having enabled both settings no channel names are displayed or written to the srvid file.

dvbapi is version 7a42b22

dvbapi.OSCamHost = 127.0.0.1
dvbapi.OSCamPort = 2000

oscam is version r11281

[dvbapi]
enabled = 1
au = 1
pmt_mode = 4
listen_port = 2000
user = vdr
read_sdt = 1
write_sdt_prov = 1
boxtype = pc

**Comment by manio** [comment]
I don't know how it is related with the plugin?

**Comment by No0ne** [comment]
I assumed oscam gets the channel info via. the tcp connection with dvbapi.
But if oscam reads the channel info by its own from the dvb device without vdr then this issue can be ignored.

**Comment by manio** [comment]
The plugin just follows oscam filtering requests - it is not passing a channel name directly in any way. Closing.

**Comment by No0ne** [comment]
Found out that it works using /tmp/camd.socket and dvbapi.OSCamNetwork = 0 on version 298a461 :(
Don't know if its a oscam or dvbapi issue.

**Comment by manio** [comment]
The plugin is not using socket mode for some time. Maybe you also need to check if this feature was *ever* working in the network mode (eg in older oscam version which was supporting this option). I think that the author of the write_sdt_prov patch maybe doesn't take into account the network mode in the dvbapi oscam module and this is the reason why it doesn't work. This is only my thought. One way or another it doesn't look like the plugin issue atm.

**Comment by No0ne** [comment]
Did work on another machine via network mode (vdr from xenial 16.04),
must be an issue with that particular machine (vdr from yakkety 16.10).

Nevertheless, thank you for your support!

**Comment by No0ne** [comment]
I discovered, when e.g. vdr is recording a new channel, the channel name is not detected.
But when I connect VLC over streamdev-server the new channel name is detected and gets written to srvid2.

Does this make sense? Whats going on here?
