### ISSUE TITLE
AES keys support

### ISSUE THREAD

**Issue by ua0lnj** [manio/vdr-plugin-dvbapi#115]
Hi.
I wrote a patch for add support of aes keys, it based on the code of tvheadend.
I wrote a patch for oscam too, and send it to oscam developers.
Please see it.
For me works fine.

[patch.zip](https://github.com/manio/vdr-plugin-dvbapi/files/787570/patch.zip)

**Comment by manio** [comment]
Really good work, ua0lnj
Thank you very much, merged!

**Comment by manio** [comment]
On 2017-02-20 14:54, ua0lnj wrote:
> Hi.
> I wrote a patch for add support of aes keys, it based on the code of
> tvheadend.
> I wrote a patch for oscam too, and send it to oscam developers.
> Please see it.
> For me works fine.

Sorry - I am not familiar with the AES decryption, I only know basics, 
and the whole idea of AES instead CSA.

Just few questions for you:
What channel/sattelite uses this AES decryption? Can I test it somehow?
If the support i already in tvheadend - how it was working if oscam 
doesn't have this support so far?
Why is your patch in oscam needed?
What is the status of oscam patch? - did you talk to some developers via 
PM or on forum? or you just wait for the ticket processing?

regards,
-- 
Mariusz Białończyk | xmpp/e-mail: manio@skyboo.net
http://manio.skyboo.net | https://github.com/manio
