### ISSUE TITLE
dosen't complie anymore :(

### ISSUE THREAD

**Issue by dersch81** [manio/vdr-plugin-dvbapi#117]
Hi, i pulled the newest version but it doesn't complie anymore:

`*** Plugin dvbapi:
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o CAPMT.o CAPMT.cpp
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o DeCSA.o DeCSA.cpp
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o DVBAPI.o DVBAPI.cpp
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o SocketHandler.o SocketHandler.cpp
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o SCCIAdapter.o SCCIAdapter.cpp
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-3c0ff1f"' -DLIBSSL -I/home/proc/vdr/include  -o SCCAMSlot.o SCCAMSlot.cpp
SCCAMSlot.cpp: In constructor ‘SCCAMSlot::SCCAMSlot(SCCIAdapter*, int, int, cCamSlot*)’:
SCCAMSlot.cpp:41:36: error: no matching function for call to ‘cCamSlot::cCamSlot(SCCIAdapter*&, bool, cCamSlot*&)’
  , decsaFillControl(200000, 100, 40)
                                    ^
SCCAMSlot.cpp:41:36: note: candidates are:
In file included from SCCAMSlot.cpp:27:0:
/home/proc/vdr/include/vdr/ci.h:156:3: note: cCamSlot::cCamSlot(cCiAdapter*, bool)
   cCamSlot(cCiAdapter *CiAdapter, bool WantsTsData = false);
   ^
/home/proc/vdr/include/vdr/ci.h:156:3: note:   candidate expects 2 arguments, 3 provided
/home/proc/vdr/include/vdr/ci.h:128:7: note: cCamSlot::cCamSlot(const cCamSlot&)
 class cCamSlot : public cListObject {
       ^
/home/proc/vdr/include/vdr/ci.h:128:7: note:   candidate expects 1 argument, 3 provided
make[1]: *** [SCCAMSlot.o] Fehler 1
`

**Comment by ua0lnj** [comment]
Which version of vdr you compiled?
Last commit for vdr-2.3.3.

**Comment by dersch81** [comment]
ah ok, i complied with 2.3.2
