### ISSUE TITLE
Problem with vdr-plugin-dvbapi and OSCAM

### ISSUE THREAD

**Issue by nmadrane** [manio/vdr-plugin-dvbapi#120]
Hi, 

I am using KODI (Libreelec) + VDR + vdr-vnsi + vdr-plugin-dvbapi. I am trying to integrate OSCAM in order to decrypt DVB-S2 channels. With unencrypted channels, everything is ok. But with encrypted channels it doesn't work. I am trying to identify where the problem is :

in VDR
in vdr-vnsi
in vdr-plugin-dvbapi
in oscam

For configuring VDR I did exactly what is mentioned in the Readme :

https://github.com/manio/vdr-plugin-dvbapi/blob/master/README

I created a remote reader in OSCAM (that  is a reader which is connected to a remote CCCAM server).

Here is the log of VDR when I try to zap top an encrypted channel :

https://pastebin.com/A9ua7fe9

Here is the log of OSCAM :

https://pastebin.com/KHmn1Xag

Could you please have a look at it and tell me if there is something wrong in the VDR log ?

In OSCAM web interface I can see that the user 'vdr' is successfully connected :

![24-08-2017 14-07-30](https://user-images.githubusercontent.com/13824239/29667824-c7258ed8-88d5-11e7-9705-7390328c0968.png)

Also, OSCAM says that it is successfully to the remote CCCAM server :

![24-08-2017 14-11-19](https://user-images.githubusercontent.com/13824239/29667995-78b98a64-88d6-11e7-90bc-ebea740b5fd9.png)

There is no ECM stuff received in OSCAM so I think vdr-plugin-dvbapi is not able to use OSCAM :

![24-08-2017 14-15-40](https://user-images.githubusercontent.com/13824239/29668075-ce2f50aa-88d6-11e7-9892-62e173f21ec6.png)

**Comment by manio** [comment]
For me it look like your VDR is wrongly configured/bad signal or something wrong with your receiving device... Are you sure you have it configured properly and channels.conf is OK?
No PMT data = no decoding.

**Comment by nmadrane** [comment]
Hi Manio, thanks for your help.

I generated a new channels.conf. Now the log is slightly different but I still get those messages "CA_PMT doesn't contain CA descriptors". Will the following log give you an idea ?

https://pastebin.com/FA68a5MJ

**Comment by manio** [comment]
You still have reception problems (CA_PMT doesn't contain CA descriptors). As this is not a VDR help thread, nor an issue I am closing it, sorry.
