### ISSUE TITLE
v2.2.4 does not compile with vdr-2.2.0 on debian stretch

### ISSUE THREAD

**Issue by satnerd** [manio/vdr-plugin-dvbapi#123]
For successfull compilation, I had to checkout version 2.2.3 of this plugin.
[Compilation-error.pdf](https://github.com/manio/vdr-plugin-dvbapi/files/1532055/Compilation-error.pdf)

**Comment by manio** [comment]
The plugin has strict compatibility list. You cannot use it on whichever vdr version you use. I am not maintaining back compatibility with older VDRs and generally it is working with recent developer versions. So you did it right - checked out the version which is working for you. Closing.
