### ISSUE TITLE
Build-Error: SCCAMSlot

### ISSUE THREAD

**Issue by utiltiy** [manio/vdr-plugin-dvbapi#124]
If got this error on arch with commit: #2a7e5dd8ce42120bb70a73eb23180b360db13b8a, i come from this commit: #d7c75875430dfdee84b04a87ad15cca0410df40b:

`SCCAMSlot.cpp: In Konstruktor »SCCAMSlot::SCCAMSlot(SCCIAdapter*, int, int, cCamSlot*)«:
SCCAMSlot.cpp:41:36: Fehler: keine passende Funktion für Aufruf von »cCamSlot::cCamSlot(SCCIAdapter*&, bool, cCamSlot*&)«
  , decsaFillControl(200000, 100, 40)
                                    ^
In file included from SCCAMSlot.cpp:27:0:
/usr/include/vdr/ci.h:156:3: Anmerkung: candidate: cCamSlot::cCamSlot(cCiAdapter*, bool)
   cCamSlot(cCiAdapter *CiAdapter, bool WantsTsData = false);
   ^~~~~~~~
/usr/include/vdr/ci.h:156:3: Anmerkung:   Kandidat erwartet 2 Argumente, 3 angegeben
/usr/include/vdr/ci.h:128:7: Anmerkung: candidate: constexpr cCamSlot::cCamSlot(const cCamSlot&)
 class cCamSlot : public cListObject {
       ^~~~~~~~
/usr/include/vdr/ci.h:128:7: Anmerkung:   Kandidat erwartet 1 Argument, 3 angegeben
make: *** [Makefile:89: SCCAMSlot.o] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

`

**Comment by manio** [comment]
What VDR version you are build against?

**Comment by utiltiy** [comment]
Stable 2.2.0

**Comment by utiltiy** [comment]
OK, why did you not split the branch between stable and develop VDR or a switch in the makefile?

**Comment by manio** [comment]
The master branch is always the development code which should work for recent VDR developer versions. I am making stable releases from time to time (https://github.com/manio/vdr-plugin-dvbapi/releases) and if you are using older VDR just use the latest stable release which is compatible with the VDR you are using. Closing.
