### ISSUE TITLE
Reopen: 

### ISSUE THREAD

**Issue by sven76** [manio/vdr-plugin-dvbapi#126]
I would like to reopen this issue: 
https://github.com/manio/vdr-plugin-dvbapi/issues/102

Got oscam with vdr-dvbapi running, when both components are on the same machine. But there's no chance to get it working, if they are installed on different machines: 

> Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: 1.1 CA_PMT decoding len=22d lm=4 prg=61200 len=218
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: ci_cmd(G)=01
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: pid=2,00ff len=0 (0x0)
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: pid=6,0103 len=0 (0x0)
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: pid=6,0030 len=0 (0x0)
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: 1.1 got CA pmt ciCmd=1 caLm=4
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: 1.1 answer to query suppressed
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: 1.1 set CAM decrypt (SID 61200 (0xEF10), caLm 4, HasCaDescriptors 1)
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: send: channelSid=0xef10 (61200)
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: Write, sock=37
Jun 25 00:56:03 htpc vdr[23872]: [23872] DVBAPI: socket_fd=37 len=567 wrote=567
Jun 25 00:56:03 htpc vdr[23872]: [23913] DVBAPI-Error: Action: read failed unknown command: 00000000
Jun 25 00:56:03 htpc vdr[23872]: [23913] DVBAPI-Error: Action: read failed unknown command: 00000000
Jun 25 00:56:03 htpc vdr[23872]: [23913] DVBAPI-Error: Action: read failed unknown command: 00000000
Jun 25 00:56:03 htpc vdr[23872]: [23913] DVBAPI-Error: Action: read failed unknown command: 00000000
Jun 25 00:56:03 htpc vdr[23872]: [23913] DVBAPI-Error: Action: read failed unknown command: ff000000

As described in the old closed bug report, in vdr switching to a encrypted channel the error occurs: channel not available. 

**Systems:** 
- Gentoo on both machines
- vdr-2.3.2
- vdr-dvbapi: 2.24 and git version 
- oscam: 1.20_p20151228 (latest version in vdr-devel overlay) and git version

**My configs:**
**/etc/vdr/setup.conf:**
`dvbapi.OSCamNetwork = 1`
`dvbapi.OSCamHost = 192.168.109.11`
`dvbapi.OSCamPort = 2000`

**/etc/oscam/oscam.conf:**
`[dvbapi]`
`enabled	      = 1`
`au            = 0`
`pmt_mode      = 4`
`listen_port   = 2000`
`user          = `
`boxtype       = pc`

**Comment by 3PO** [comment]
Your oscam is to old.
You can use the ebuild from my overlay.

https://github.com/3PO/3PO-overlay

**Comment by manio** [comment]
No further input - closing...
