### ISSUE TITLE
For the old SC Plugin a FIX for SKY, cann integrat in thies Plugin?

### ISSUE THREAD

**Issue by gitpower2017** [manio/vdr-plugin-dvbapi#129]
Hello,

this is a FIX for the old SC Plugin.

https://github.com/3PO/vdr-plugin-sc/blob/master/cam.c#L2631

Can where integrate in this Plugin?

**Comment by pipelka** [comment]
Maybe this:
http://www.streamboard.tv/wiki/OSCam/de/Config/oscam.server#disablecrccws
will help you.

**Comment by manio** [comment]
@gitpower2017
Does it help?

**Comment by manio** [comment]
No response for over a year, closing.
