### ISSUE TITLE
I can t get connection with oscam 

### ISSUE THREAD

**Issue by spein46** [manio/vdr-plugin-dvbapi#136]
Hi, I m trying to connect vdr and oscam with this plugin, I think set up all good but it dosen t work, can you help me
I use skystar2 dvb-s card and last oscam, vdr, vdr-plugin-dvbapi version
oscam log:

> 2020/09/05 21:51:26 256CB42F c   (dvbapi) Read 0 entries from oscam.dvbapi
2020/09/05 21:51:26 256CB42F c   (dvbapi) dvbapi channelcache loaded from /usr/local/etc/oscam.ccache
2020/09/05 21:51:26 256CB42F c   (dvbapi) Using TCP listen socket, API forced to DVBAPIv3 (0), userconfig boxtype: 

> 11

this is the log syslog:

> Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] VDR version 2.4.0 started
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] codeset is 'UTF-8' - known
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] found 28 locales in /usr/share/locale
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading plugin: /usr/lib/vdr/plugins/libvdr-dvbapi.so.2.4.0
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/setup.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/sources.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/diseqc.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/scr.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/channels.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/commands.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/reccmds.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/svdrphosts.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/remote.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/keymacros.conf
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] registered source parameters for 'A - ATSC'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] registered source parameters for 'C - DVB-C'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] registered source parameters for 'S - DVB-S'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] registered source parameters for 'T - DVB-T'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29092] video directory scanner thread started (pid=29091, tid=29092, prio=low)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29093] epg data reader thread started (pid=29091, tid=29093, prio=high)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] probing /dev/dvb/adapter0/frontend0
Sep  5 22:10:53 spein-System-Product-Name vdr: [29092] video directory scanner thread ended (pid=29091, tid=29092)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] creating cDvbDevice
Sep  5 22:10:53 spein-System-Product-Name vdr: [29093] reading EPG data from /var/cache/vdr/epg.data
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] new device number 1
Sep  5 22:10:53 spein-System-Product-Name vdr: [29093] epg data reader thread ended (pid=29091, tid=29093)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVB API version is 0x050B (VDR was built with 0x050A)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] frontend 0/0 provides DVB-S with QPSK ("ST STV0299 DVB-S")
Sep  5 22:10:53 spein-System-Product-Name vdr: [29095] frontend 0/0 tuner thread started (pid=29091, tid=29095, prio=high)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] cTimeMs: using monotonic clock (resolution is 1 ns)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29095] cTimeMs: using monotonic clock (resolution is 1 ns)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] found 1 DVB device
Sep  5 22:10:53 spein-System-Product-Name vdr: [29096] device 1 section handler thread started (pid=29091, tid=29096, prio=low)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] initializing plugin: dvbapi (2.2.5-GIT-197e752): SoftCAM for OSCam
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] setting primary device to 1
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] device 1 has no MPEG decoder
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] assuming manual start of VDR
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] setting current skin to "lcars"
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/lib/vdr/themes/lcars-default.theme
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] starting plugin: dvbapi
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: plugin version 2.2.5-GIT-197e752 initializing (VDR 2.4.0)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: decryption library: FFdecsa
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: clustersize=140 rangesize=285
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: ResetState
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: SocketHandler
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: Creating sCCIAdapter
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: Creating SCCAMSlot for device 1
Sep  5 22:10:53 spein-System-Product-Name vdr: [29097] Socket Handler thread started (pid=29091, tid=29097, prio=high)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: ResetSlot: log=0
Sep  5 22:10:53 spein-System-Product-Name vdr: [29097] DVBAPI: Action
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: plugin started
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] SC-CI adapter thread started (pid=29091, tid=29098, prio=high)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] remote control KBD - keys known
Sep  5 22:10:53 spein-System-Product-Name vdr: [29099] KBD remote control thread started (pid=29091, tid=29099, prio=high)
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] loading /var/cache/vdr/cam.data
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0: doReply changed, reset triggered
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] DVBAPI: ResetSlot: log=0
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0: now using CAIDs version 1
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0: status 'present'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29098] CAM 1: module present
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: 0.0: status 'reset'
Sep  5 22:10:53 spein-System-Product-Name vdr: [29091] DVBAPI: 0.0: status 'ready'
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] CAM 1: module ready
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: CaInfo: 0.0 sending CA info
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] CAM 1: system ids: FFFF
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0 CA_PMT decoding len=7 lm=3 prg=0 len=1
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: ci_cmd(G)=03
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0 got CA pmt ciCmd=3 caLm=3
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0 answer to query
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] DVBAPI: 0.0 no action taken
Sep  5 22:10:54 spein-System-Product-Name vdr: [29098] CAM 1: replies to QUERY - multi channel decryption (MCD) possible
Sep  5 22:10:54 spein-System-Product-Name vdr: [29091] CAM 1: ready, master (OSCam)
Sep  5 22:10:54 spein-System-Product-Name vdr: [29091] switching to channel 1 S13.0E-64511-9600-1407 (La7)

>

**Comment by manio** [comment]
Hi, did you solved this? Can we close it?

**Comment by manio** [comment]
No contact with author's issue - closing for now...
