### ISSUE TITLE
get_pmt read error

### ISSUE THREAD

**Issue by splinux** [manio/vdr-plugin-dvbapi#16]
Hello,

I use vdr-plugin-dvbapi togheter with yavdr 0.5.0 and oscam svn (now rev 7943)
It is working correctly, except sometimes (often) when I zap from channel to channel i get following errors. Sometimes it is after 1 zap, sometimes 10 and not always on the same channels. 

Nov 28 08:25:51 pccave vdr: [6895] DVBAPI-Error: get_pmt: read_sections: read error: Connection timed out

Nov 28 08:25:51 pccave vdr: [6895] DVBAPI-Error: Error obtaining PMT data, returning

I then need to reboot vdr.
Don't know if it is dvbapi or oscam related, but can't find the solution.
Any idea what could be the reason of the read error.
Thanks
SP

**Comment by wilb** [comment]
I know this is pulling something up from the dead, but I appear to be having issues along the lines described in this thread and they've been fixed (or worked around at least) by the commit referenced above (rev: a98ff1e)

I'm currently using YaVDR 0.5.0 with the latest stable vdr package they are distributing, along with the community maintained builds of oscam and dvbapi to match:
 
 vdr -  2.0.6-6yavdr1
 oscam-upstart-svn9850 - 1.20-svn9850.20141016.1925-1~precise
 vdr-plugin-dvbapi - 1.0.6.git20140424.1608-1~precise 

As a background, I have a dual tuner setup - one on a fixed dish, one on a GotoX rotor, driven using the gotox patch and configure through diseqc.conf . As such there are often valid cases in which I may zap a channel and VDR thinks there is no signal, but a few seconds later a lock will arrive and off we go. I also have some cases where I haven't zapped a channel in a while and maybe the line in channels.conf is out of date, but generally the "add new transponders" setting will keep on top of this.

This evening I've been able to narrow this down a bit to a constantly reproducible state where VDR ends up blocking out the use of a CAM on a particular tuner, resulting in me only being able to get FTA channels unless I restart VDR. I can make this happen on both my fixed dish and on my rotor seemingly by tuning to an encrypted channel that oscam cannot decrypt. If i leave this a few seconds, the result is that I get a "channel not available" message back from VDR when I try and tune the same tuner to another encrypted channel and have to restart VDR to fix it.

This thread came to my attention so I've just pulled down the commit above, built it manually and dropped it in place of my packaged DVBAPI library. I now have infinitely more graceful behaviour but at the cost of being even further back in time with my dvbapi library than I was before.

I'm tempted to do a wholesale upgrade of vdr / oscam / dvbapi but I worry that I'll encounter the same issue as it's a bit of an edge case...

**Comment by manio** [comment]
Hello wilb,
In fact the problem you described was one of the main benefit after rewriting my plugin to use a new CAM interface provided by the current VDR versions. Currently even stable VDR has this feature so I strongly urge you to update your VDR to not use this old (and unsupported currently by me) VDR versions and dvbapi plugin.
Please just use the newest stable VDR and current dvbapi plugin. I think it should work much more stable and robust for you. My plugin is not obtaining PMT itself. VDR is prepared for constantly trying to tune and then attach/detach the CAM.

**Comment by wilb** [comment]
Thanks for the clarity on that. I used to be well into keeping on top of my VDR box back when I had more time but moved over to using the YaVDR distro for simplicity which is the reason why I'm behind the times. Given what you've said I'll set aside a bit of time to get things up to date though.

Thanks!

**Comment by wilb** [comment]
Just in case anyone else stumbles upon this thread I can confirm that upgrading everything has resulted in a nice working setup. :+1:
