### ISSUE TITLE
No EMMs in Network Mode

### ISSUE THREAD

**Issue by 3PO** [manio/vdr-plugin-dvbapi#52]
In Network Mode the dvbapi-Plugin do not sent any EMM Requests.

"AU" is enabled for "dvbapi" and "user"

oscam.conf: (<-- on oscam Server)

>[dvbapi]
>enabled                       = 1
>au                            = 1
>pmt_mode                      = 4
>request_mode                  = 1
>listen_port                   = 4444
>delayer                       = 300
>user                          = vdr_dvbapi
>boxtype                       = pc

oscam.user (<-- on oscam Server)

>[account]
disabled                      = 0
user                          = vdr_dvbapi
pwd                           = 
sleep                         = 0
suppresscmd08                 = 0
keepalive                     = 1
au                            = 1
emmreassembly                 = 2
betatunnel                    = 1833.FFFF:1702
>group                         = 1,2,3,4,5,6,7,8,9,10

**Comment by manio** [comment]
Closing this issue, as the new VDR 2.1.7 has this feature/patch (and other EMM handling fixes) finally in :)
