### ISSUE TITLE
dropouts in nw mode (with -o option) when zapping

### ISSUE THREAD

**Issue by goerdi** [manio/vdr-plugin-dvbapi#76]
Hi !
I habe 2 clients in NW mode (one starts with -o2) when i watch an encypted channel on client 1 and on client 2 i zapp through crypted channels i have dropouts on clint 1

**Comment by gerdigerdi** [comment]
Hello!
I have the same problem with 3 SAT budget devices in my PC. Dvbapi does not always forward the reqests to oscam when changing the channels. It depends on the used card.
It always fails after .... [DVBAPI] Demuxer #0 continue decoding of ...
It would be really nice if the dvbapi will work corrrectly with multiple adapters.
I can send you detailed logs if still needed.
Have a nice new year!

**Comment by manio** [comment]
@gerdigerdi
My plugin correctly supports decoding on multiple adapters. The problem here in this ticket is even not diagnosed - because @goerdi has not provided additional information. Closing.

If you have problems after "Demuxer #0 continue decoding of" ... please create a ticket in the OSCam trac system, because it is probably related (my plugin doesn't influence on this behavior).

**Comment by 3PO** [comment]
--> http://dreipo.cc/forum/viewtopic.php?f=10&t=11   ;)

**Comment by gerdigerdi** [comment]
Thanks a lot! The vdr version was buggy. Patching does the trick ;)
Your plugin is working perfectly :)

**Comment by CReimer** [comment]
Because these three patches are hidden behind a login form I uploaded the into my Github Gist
https://gist.github.com/CReimer/d969786d7f9bd9f00f3d

@manio: Could you make a comment upon these patches? Do you think they are safe to use?

**Comment by manio** [comment]
I think that Klaus should comment upon these. I just think that if the previous values was not enough, than it needs to be adjusted and it should be upstreamed. The same apply to the CAM assigning patch. So please guys let him know about this patches.

**Comment by 3PO** [comment]
Klaus knows about this Problem. ;)
