### ISSUE TITLE
remote CCcam not work

### ISSUE THREAD

**Issue by marian3** [manio/vdr-plugin-dvbapi#86]
Hi, my set is vdr2.2.0+oscam10614.Remote newcamd ok:
<pre><code>
14:03:49  9285388 c   (dvbapi) Client connected: 'vdr-plugin-dvbapi 2.2.0 / VDR 2.2.0' (protocol version = 1)
<br>14:03:49  9285388 c   (dvbapi) Demuxer 0 added new ecmpid 0 CAID: 0D96 ECM_PID: 047C PROVID: 000000
<br>14:03:49  9285388 c   (dvbapi) Demuxer 0 added new ecmpid 1 CAID: 0624 ECM_PID: 0486 PROVID: 000000
14:03:49  9285388 c   (dvbapi) Demuxer 0 added new ecmpid 2 CAID: 0666 ECM_PID: 0490 PROVID: 000000
14:03:49  9285388 c   (dvbapi) Demuxer 0 found 3 ECMpids and 2 STREAMpids in PMT
14:03:49  9285388 c   (dvbapi) Demuxer 0 receiver wants to demux srvid 13F4 on adapter 0000 camask 0001 index 0000 pmtpid 0000
14:03:49  9285388 c   (dvbapi) Demuxer 0 new program number: 13F4 (0D96:13F4 unknown) [pmt_list_management 3]
14:03:49  9285388 c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0D96 PROVID 000000 ECMPID 047C ANY CHID PMTPID 0000 VPID 03FA
14:03:50  9284E80 p   (reader) 192.168.1.11: resolved ip=192.168.1.11
14:03:50  9284E80 p   (reader) newcamd_vdr [newcamd] connecting to 192.168.1.11:11112
14:03:50  9284E80 p  (newcamd) Newcamd Server: 192.168.1.11:11112 - UserID: 1
14:03:50  9284E80 p  (newcamd) CAID: 0D96 - UA: 00100E24CE000000 - Provider # 4
14:03:50  9284E80 p  (newcamd) Provider ID: 000004 - SA: 00000000
14:03:50  9284E80 p  (newcamd) Provider ID: 000008 - SA: 00000000
14:03:50  9284E80 p  (newcamd) Provider ID: 00000C - SA: 00000000
14:03:50  9284E80 p  (newcamd) Provider ID: 000010 - SA: 00000000
14:03:50  9285388 c      (ecm) vdr (0D96&000004/0000/13F4/80:0049014A6246D67EB5154D17D021D6C7): found (275 ms) by newcamd_vdr
14:04:00  9285388 c      (ecm) vdr (0D96&000004/0000/13F4/80:0049014A6246D67EEDB2BF5E9766E7E4): found (234 ms) by newcamd_vdr</code></pre>
while remote cccam(tested) not work:
<pre><code>13:54:13  8D89380 c   (dvbapi) Client connected: 'vdr-plugin-dvbapi 2.2.0 / VDR 2.2.0' (protocol version = 1)
13:54:13  8D89380 c   (dvbapi) Demuxer 0 added new ecmpid 0 CAID: 0D96 ECM_PID: 047C PROVID: 000000
13:54:13  8D89380 c   (dvbapi) Demuxer 0 added new ecmpid 1 CAID: 0624 ECM_PID: 0486 PROVID: 000000
13:54:13  8D89380 c   (dvbapi) Demuxer 0 added new ecmpid 2 CAID: 0666 ECM_PID: 0490 PROVID: 000000
13:54:13  8D89380 c   (dvbapi) Demuxer 0 found 3 ECMpids and 2 STREAMpids in PMT
13:54:13  8D89380 c   (dvbapi) Demuxer 0 receiver wants to demux srvid 13F4 on adapter 0000 camask 0001 index 0000 pmtpid 0000
13:54:13  8D89380 c   (dvbapi) Demuxer 0 new program number: 13F4 (0D96:13F4 unknown) [pmt_list_management 3]
13:54:13  8D89380 c   (dvbapi) Demuxer 0 no suitable readers found that can be used for decoding!
13:54:14  8D89380 c   (dvbapi) Demuxer 0 no enabled matching ecmpids -> decoding is waiting for matching readers!</code></pre>

**Comment by manio** [comment]
Invalid. Please report to OSCam. It is not related with dvbapi plugin. Besides the "no suitable readers found" generally means that you have a problem in the OSCam configuration. Closing.
