### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by AndreyPavlenko** [manio/vdr-plugin-dvbapi#89]
Hi,

I'm trying to build the plugin for armhf but getting the following errors:

g++: error: unrecognized command line option '-mmmx'
g++: error: unrecognized command line option '-msse'
g++: error: unrecognized command line option '-msse2'
g++: error: unrecognized command line option '-msse3'

Could you please add support for ARM architectures?

**Comment by manio** [comment]
https://github.com/manio/vdr-plugin-dvbapi/blob/master/INSTALL#L18

**Comment by AndreyPavlenko** [comment]
Thanks Mariusz.
Will try to compile against libdvbcsa.
