### ISSUE TITLE
Freeze on providers with cw time more 20 sec.

### ISSUE THREAD

**Issue by fantomkas** [manio/vdr-plugin-dvbapi#90]
Please apply this patch for long cw lifetime providers.

--- vdr-plugin-dvbapi-2.2.0-472~fd4fcd6.orig/DeCSA.h
+++ vdr-plugin-dvbapi-2.2.0-472~fd4fcd6/DeCSA.h
@@ -32,7 +32,7 @@ extern "C" {
.
 #define MAX_CSA_PIDS 8192
 #define MAX_CSA_IDX  16
-#define MAX_KEY_WAIT 20         // max seconds to consider a CW as valid
+#define MAX_KEY_WAIT 25         // max seconds to consider a CW as valid
.
 #include "DVBAPI.h"
.
Thank you!

**Comment by manio** [comment]
What provider you mean exactly?

**Comment by fantomkas** [comment]
Russian provider KontinentTV 85E (caid 0602 irdeto) and Telekarta 85E (caid 0b01 conax).

**Comment by manio** [comment]
merged, thx :)
