### ISSUE TITLE
descrambling stops after a few seconds on certain channels

### ISSUE THREAD

**Issue by maxodoble** [manio/vdr-plugin-dvbapi#94]
Hello,

yesterday i noticed, that on certain channels (ORF2 ST HD and ORF III HD) the descrambling stops after a few seconds. When tuning in, the channel starts ok, and after  a few seconds freezes. retuning starts the channel again, and after a few seconds freezes again.

Logs:
http://pastebin.com/1JrVA3UP

as far as i have seen, all other channels are descrambled ok, no freezes.

in oscam log i see just one ecm line on the mentioned channels:
"dvbapi (0D95&000004/0000/33F5/B8:5413FE672142BAD2E3D0A2CAE5F2DBBB): found (482 ms) by cccam", no ecm updates follow, after first tune in.

on the working channels there are updated ecm lines regularly in the oscam log.

any idea what might cause this odd behavior?

Max

**Comment by manio** [comment]
What if you disable the expiration check?
https://github.com/manio/vdr-plugin-dvbapi/blob/master/README#L164

**Comment by maxodoble** [comment]
Hi,
tried it and yes with disabled expiration check everything works.

Thanks much!

**Comment by manio** [comment]
Thx, closing.

**Comment by vdrfan** [comment]
hello maxodoble,
is your problem solved?
can you make a periodical timer to test ORF2 ST HD, i think this is randomly(20 hours every 7. day).
thanks, vdrfan.
