### ISSUE TITLE
artefacts only in combination with satip

### ISSUE THREAD

**Issue by pvdputte** [manio/vdr-plugin-dvbapi#95]
Hi,

Your plugin has been working absolutely wonderfully for a long time, decrypting channels fed by my three PCI DVB-S2 cards, in network mode. Config:
vdr 2.2.0 -> vdr-plugin-dvbapi (git master) -> oscam 1.20-10887 -> smargo reader -> smartcard (official M7/TV Vlaanderen).
All on the same host.

Lately one DVB card broke down and I decided to replace it with an Inverto/Grundig/Telestar idl4k SAT>IP device (Telestar Digibit R1).

The satip device (firmware 1.17) + vdr-plugin-satip works totally fine for FTA broadcasts. Recording 3 HD channels using three tuners + streaming 2 HD channels live from the same transponder: not a sweat.

However, when I do something less stressing with encrypted channels, it does not take long for artefacts to appear. E.g. recording 2 HD channels and watching 1 live works for a couple of minutes, but usually one of them starts experiencing severe video and sound artefacts.

I've tried different satip firmwares (1.16, 1.17, and https://github.com/perexg/satip-axe/) as well as different vdr hardware (dual and quad core Intel systems with 2 and 4GB RAM and a fast disk).

I'm suspecting there is some buffering going on and some data is occasionally being dropped for an unknown reason.

I've monitored the oscam logs and I don't see anything unusal (found always within 250-350ms).

Can you make a suggestion how to proceed troubleshooting or what buffers may be in play here and how I can tune them?

Thanks, and thanks for the fine plugin.

**Comment by manio** [comment]
So you have this artefacts only on the satip device? What if you decrypt the same channel on regular DVB-S2 card?

**Comment by pvdputte** [comment]
When decrypting the same channels via DVB-S2 cards, there are no problems. I've been focussing my attention on the satip device while troubleshooting the past week, without finding anything tangible. As FTA channels look good even when stressing the setup, I've begun trying to understand how the decryption actually takes place (e.g. data being buffered somehwere until decryption key is available etc.).

Perhaps a satip data stream is more jittery, which may not be a problem for FTA, but perhaps it triggers unexpected behavior when it needs to be decrypted? I'm just wild-guessing here.

**Comment by manio** [comment]
If you are asking about buffering - it is now done in the VDR.
Unfortunately I don't know how to help you - moreover I don't have such hardware :(

You can try eg tvheadend if it meet your needs. It has a native support for satip devices if it convince you somehow.

**Comment by pvdputte** [comment]
Actually, I come from mythtv + vdr-sasc-ng and I was very very pleased with VDR after making the jump. No broken channel scanner anymore but just a channels.conf file etc. :-)

The hardware is actually quite nice for the price, and alternative firmware like https://github.com/perexg/satip-axe/tree/master/dist opens many possibilities.

I'll look into https://github.com/catalinii/minisatip/issues/21 as I see mention of a vdr 'decode buffer' and 'buffer stats' log messages, maybe I can learn something from that if I increase logging. (I already tried the network buffer thing but no luck)

If I can't find anything I'll have to buy another PCI card I'm afraid.

Thank you for your time!

**Comment by manio** [comment]
Yeah, the tvheadend also comes from perexg :)

In this case I'll close the issue if you don't mind. Thanks.

**Comment by pvdputte** [comment]
Hi,

Just FYI, after more stresstesting with TVHeadend I managed to get similar results with FTA broadcasts. I needed to stress it a *lot* more though. I suspect the errors are always there in FTA streams as well, but when the stream needs to be decrypted the impact of missing data is perhaps bigger and more visible.

I guess I should have bought a more expensive device :-(
