### ISSUE TITLE
Failure of dvbapi that was compiled on an arm using LIBDVBCSA=1

### ISSUE THREAD

**Issue by chtugha** [manio/vdr-plugin-dvbapi#96]
I'm trying to build oscam + dvbapi for vdr-2.2.0 on Banana pi with Bananian (wheezy).

It compiles fine using command

     make clean
     make -j4 LIBDVBCSA=1 plugins

and installs also OK.

But when running the vdr, it fails:

vdr: /usr/local/lib/vdr/libvdr-dvbapi.so.2.2.0: undefined symbol:
_Z21set_even_control_wordPvPKh

**Comment by manio** [comment]
You may try this: go into directory with plugin sources and 'make clean' there, then go into vdr main source directory and there make plugins as usual.

**Comment by chtugha** [comment]
Thank you for your reply.
I tried that - nothing changed. If I build as usual (without LIBDVBCSA=1), it won't compile (no -mmx etc..). Compiling with libdvbcsa brings up the above Error. Seems like somebody else got that Problem too (http://comments.gmane.org/gmane.linux.vdr/48635).
I will try to set up vdr from scratch tonight and report if the Error is replicable.

**Comment by chtugha** [comment]
Now I went the debian way and tried to build a Package (dpkg-buildpackage -us -uc) after running debianize-vdrplugin.
The make options set in /debian/rules are: VDRDIR=/usr/include/vdr LIBDIR=/usr/lib/vdr/plugins LIBDVBCSA=/usr/lib/vdr/plugins LOCALEDIR=locale

Whatever I try, I don't get past this error.
/usr/bin/ld: CAPMT.o: relocation R_ARM_THM_MOVW_ABS_NC against `LogLevel' can not be used when making a shared object; recompile with -fPIC
CAPMT.o: could not read symbols: Bad value
collect2: ld returned 1 exit status

adding -fPIC to the make options just produces another Error.
Any Idea?
Thanks

**Comment by chtugha** [comment]
Couldn't replicate it ... works like a charm now. But all attempts to build a debian package failed :) - compiled fine using debian/rules (initialy made by debianize-dvbplugin):

export LIBDVBCSA=1
MAKE_OPTIONS = VDRDIR=/usr/include/vdr LIBDIR=/usr/lib/vdr/plugins LOCALEDIR=locale CFLAGS+=-fPIC CXXFLAGS+=-fPIC

but failed in the end saying that dh_make couldn't find a file it already compiled..... maybe someone could try to fix this :)

Thanks for your time and effort !!

**Comment by manio** [comment]
Ah, good it is working. Regarding the debian package - sorry, I am not familiar with it... Anyway - closing the issue. Thanks for your input.
