### ISSUE TITLE
descrambling stops after a few seconds on certain channels

### ISSUE THREAD

**Issue by vdrfan** [manio/vdr-plugin-dvbapi#97]
Hello,
i have the same issue like maxodoble on #94
https://github.com/manio/vdr-plugin-dvbapi/issues/94

disable the expiration check doesn't help.
no change with CheckExpiredCW=true or false.
deycryption stops after 25s on all channels on transponder orf 12692.
sounds like MAX_KEY_WAIT, but when looking at the code it has nothing todo with MAX_KEY_WAIT.

sc has no problems, and dvbapi has no problem on other channels.

the problem exist randomly (i have a peridiodical rec. timer on that channel)
08.06.2015 NOT OK
09.06.2015-14.06.2015 OK
15.06.2015 NOT OK
16.06.2015-12.06.2015 OK
23.06.2015 NOT OK
24.06.2015-06.07.2015 OK
07.07.2015 NO OK but OK since 19:10

tried to find the bug in: cDvbapiFilter::Analyze, but...

maybe this will help:
when recording channel it stops after 25s.
when makeing second recording on same channel, the first recording will also continue recording for 25s.

any idea,
vdrfan.

**Comment by manio** [comment]
You sure you correctly used the expiration CW switch? Did you have a notification in the vdr log about it?
Can you try the socket mode? This way we will eliminate the plugin filtering code.

**Comment by vdrfan** [comment]
hi, i tiried to send you email with logs (mail adress wrong?). 

i have noticed CW in the log, and i have also forced to true and false direct in code.
i cannot test at this time in socket mode - but will do next time the problem occurs.
its strange but i think it will happen again from monday to tuesday.

I tried to fix it by myself – but i have only a couple of hours to test, because the problem disapears by itself. and also I am not fit in scrambled content…

i think it has do to with CW but CW dont gets updated - for any reason.

Can you explain what is cDvbapiFilter::Analyze exactly for?
Maybe it should also get called when TS_SCRAMBLING_CONTROL is set and Decrypt is returning false or something…  (maybe the provider is sending garbage on that time).

In: cDvbapiFilter::Analyze
There could be a problem in the code segment:
if (i == max)
{}
else 
{Maybe we have here also a part of this filter?}

In: cDvbapiFilter::Analyze
else if (it->data && (cc == it->lastcc + 1))
{ Shouldn’t we check here also for tablelen? }

thanks, vdrfan

**Comment by manio** [comment]
Ok. We discussed the problems via e-mail. If you can not reproduce the problem anymore, can we close this issue?

**Comment by vdrfan** [comment]
hi, never happened again, we can close this issue....
thanks to your work manio.
