### ISSUE TITLE
ecmhandler needs updating to work properly with oscam r10985 or newer

### ISSUE THREAD

**Issue by bacon-cheeseburger** [manio/vdr-plugin-dvbapi#99]
From the oscam commit log:

Changeset 10985 for trunk
Timestamp:     09/08/15 02:48:43
Author:    theparasol
Message:

    DVBAPI:

        More fix for ecmpid prio code
        Ecmhandler fixes the provid, dvbapi needs to do the same otherwise controlword handling fails!

**Comment by manio** [comment]
I am now using oscam r10991 without any problems. And I was also talking to theparasol - he doesn't know about any problems or changes which should be made because of this (or related) commits.

**Comment by manio** [comment]
Fixed in [rev 10992](http://www.streamboard.tv/oscam/changeset/10992).
